"use client";

import { HoloCard } from "@/components/ui/HoloCard";
import { FileText, Download, CheckCircle } from "lucide-react";
import jsPDF from "jspdf";
import { useState } from "react";

export default function ReportsPage() {
  const [downloading, setDownloading] = useState<number | null>(null);

  const generatePDF = (id: number) => {
    setDownloading(id);
    
    setTimeout(() => {
      const doc = new jsPDF();
      
      // Background dark slate
      doc.setFillColor(5, 8, 22); 
      doc.rect(0, 0, 210, 297, 'F');
      
      // Header
      doc.setTextColor(0, 245, 255);
      doc.setFontSize(24);
      doc.setFont("helvetica", "bold");
      doc.text("SENTINEL AI - INTELLIGENCE REPORT", 20, 30);
      
      doc.setDrawColor(0, 245, 255);
      doc.setLineWidth(0.5);
      doc.line(20, 35, 190, 35);
      
      // Metadata
      doc.setTextColor(200, 200, 200);
      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      doc.text(`REPORT IDENTIFIER: RPT-2026-${id}A9F`, 20, 50);
      doc.text(`GENERATION DATE: ${new Date().toLocaleString()}`, 20, 60);
      doc.text("INCIDENT VECTOR: Authentication Microservice Cascading Failure", 20, 70);
      
      doc.setTextColor(0, 255, 157); // Emerald
      doc.text("MEAN TIME TO RESOLUTION (MTTR): 14.3 Minutes", 20, 80);
      doc.setTextColor(139, 92, 246); // Purple
      doc.text("AI CONFIDENCE SCORE: 98.7%", 20, 90);
      
      // Body
      doc.setTextColor(0, 245, 255);
      doc.setFontSize(16);
      doc.setFont("helvetica", "bold");
      doc.text("AUTONOMOUS ROOT CAUSE ANALYSIS", 20, 110);
      
      doc.setTextColor(180, 180, 180);
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      
      const analysisText = [
        "At 04:15:22 UTC, the Sentinel AI Root Cause Analyzer detected a massive spike in memory",
        "allocation within the primary authentication service cluster (eu-west-1).",
        "",
        "The Correlation Engine successfully linked this spike to a malformed JWT token parsing",
        "loop introduced in deployment v4.1.9.",
        "",
        "ACTION TAKEN:",
        "1. Sentinel AI automatically isolated the affected region.",
        "2. The Recovery Planner initiated a rollback to v4.1.8.",
        "3. Traffic was dynamically rerouted to the us-east-1 replica set.",
        "",
        "SYSTEM STATUS: FULLY RECOVERED."
      ];
      
      doc.text(analysisText, 20, 125);
      
      // Footer
      doc.setDrawColor(50, 50, 50);
      doc.line(20, 280, 190, 280);
      doc.setFontSize(8);
      doc.setTextColor(100, 100, 100);
      doc.text("GENERATED BY SENTINEL AI ENGINE • CLASSIFICATION: CONFIDENTIAL", 20, 285);
      
      doc.save(`Sentinel_PostMortem_Report_${id}.pdf`);
      setDownloading(null);
      
      if ((window as any).triggerToast) {
        (window as any).triggerToast("REPORT PDF GENERATED & DOWNLOADED", "success");
      }
    }, 1500); // Cinematic artificial delay
  };

  return (
    <div className="flex flex-col gap-6 h-full p-6 relative">
      <div className="flex items-center justify-between relative z-10">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl bg-brand-cyan/10 flex items-center justify-center border border-brand-cyan/30 shadow-[0_0_20px_rgba(0,245,255,0.2)]">
            <FileText className="w-6 h-6 text-brand-cyan" />
          </div>
          <div>
            <h1 className="text-3xl font-black tracking-tight text-foreground text-glow-cyan">ENTERPRISE ANALYTICS SYSTEM</h1>
            <p className="text-xs font-mono tracking-widest text-brand-cyan/60 uppercase">AI-generated post-mortem reports</p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 h-full">
        {[1, 2, 3].map((i) => (
          <HoloCard key={i} className="p-8 flex flex-col justify-between group" glowColor="cyan">
            <div>
              <div className="flex items-center justify-between mb-6">
                <div className="w-16 h-16 rounded-full bg-slate-900 border-2 border-brand-cyan/50 flex items-center justify-center shadow-[0_0_15px_rgba(0,245,255,0.3)]">
                  <FileText className="w-8 h-8 text-brand-cyan" />
                </div>
                <span className="text-xs font-bold font-mono tracking-widest text-slate-500 bg-slate-900 px-3 py-1 rounded-md border border-slate-800">MAY 2026</span>
              </div>
              <h3 className="text-xl font-bold text-slate-200 mb-3 leading-tight group-hover:text-brand-cyan transition-colors">
                Major Outage: Auth Service Cascading Failure
              </h3>
              <p className="text-sm font-mono text-slate-400 mb-8 leading-relaxed">
                Automatically generated by Incident Report Agent.
                <br/><br/>
                <span className="text-brand-emerald font-bold">MTTR: 14m</span> | <span className="text-brand-purple font-bold">Confidence: 98%</span>
              </p>
            </div>
            
            <button 
              onClick={(e) => {
                // Prevent global toast from firing generic action since we want our specific custom logic
                e.stopPropagation(); 
                generatePDF(i);
              }}
              disabled={downloading === i}
              className={`flex items-center justify-center gap-2 w-full py-4 font-bold tracking-widest rounded-xl transition-all border shadow-[0_0_15px_rgba(0,245,255,0.1)] ${
                downloading === i 
                  ? "bg-slate-800 border-slate-600 text-slate-400" 
                  : "bg-brand-cyan/10 hover:bg-brand-cyan/20 text-brand-cyan border-brand-cyan/30 hover:border-brand-cyan/60"
              }`}
            >
              {downloading === i ? (
                <>
                  <div className="w-4 h-4 border-2 border-slate-400 border-t-transparent rounded-full animate-spin"></div>
                  GENERATING PDF...
                </>
              ) : (
                <>
                  <Download className="w-4 h-4" /> EXPORT PDF
                </>
              )}
            </button>
          </HoloCard>
        ))}
      </div>
    </div>
  );
}
