"use client";

import { useGlobalState } from "@/lib/store/GlobalStateProvider";
import { HoloCard } from "@/components/ui/HoloCard";
import { Briefcase, TrendingUp, DollarSign, Activity, AlertCircle } from "lucide-react";
import { MetricsChart } from "@/components/charts/MetricsChart";

export default function ExecutivePage() {
  const { metrics } = useGlobalState();
  const uptime = (metrics.system_health).toFixed(3);
  const revenueAtRisk = (100 - metrics.system_health) * 12500; // Fake calculation for cinematic effect

  return (
    <div className="flex flex-col gap-6 h-full p-6 relative">
      <div className="flex items-center justify-between relative z-10">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl bg-brand-amber/10 flex items-center justify-center border border-brand-amber/30 shadow-[0_0_20px_rgba(255,183,3,0.2)]">
            <Briefcase className="w-6 h-6 text-brand-amber" />
          </div>
          <div>
            <h1 className="text-3xl font-black tracking-tight text-foreground text-glow-amber">EXECUTIVE INTELLIGENCE DASHBOARD</h1>
            <p className="text-xs font-mono tracking-widest text-brand-amber/60 uppercase">Business impact and global SLA analytics</p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
         <HoloCard className="p-6" glowColor="emerald">
            <div className="flex items-center gap-3 mb-2 text-brand-emerald">
               <TrendingUp className="w-5 h-5" />
               <h3 className="text-sm font-bold tracking-widest">SLA UPTIME (30D)</h3>
            </div>
            <div className="text-4xl font-black font-mono text-foreground">{uptime}%</div>
         </HoloCard>
         
         <HoloCard className="p-6" glowColor={revenueAtRisk > 50000 ? "red" : "amber"}>
            <div className="flex items-center gap-3 mb-2 text-brand-amber">
               <DollarSign className="w-5 h-5" />
               <h3 className="text-sm font-bold tracking-widest">REVENUE AT RISK</h3>
            </div>
            <div className={`text-4xl font-black font-mono ${revenueAtRisk > 50000 ? "text-brand-crimson text-glow-crimson animate-pulse" : "text-foreground"}`}>
               ${revenueAtRisk.toLocaleString(undefined, { maximumFractionDigits: 0 })}
            </div>
         </HoloCard>

         <HoloCard className="p-6" glowColor="cyan">
            <div className="flex items-center gap-3 mb-2 text-brand-cyan">
               <Activity className="w-5 h-5" />
               <h3 className="text-sm font-bold tracking-widest">AI INCIDENTS RESOLVED</h3>
            </div>
            <div className="text-4xl font-black font-mono text-foreground text-glow-cyan">1,204</div>
         </HoloCard>

         <HoloCard className="p-6" glowColor="purple">
            <div className="flex items-center gap-3 mb-2 text-brand-purple">
               <AlertCircle className="w-5 h-5" />
               <h3 className="text-sm font-bold tracking-widest">MTTR (AI ASSISTED)</h3>
            </div>
            <div className="flex items-baseline gap-2">
              <div className="text-4xl font-black font-mono text-foreground">14</div>
              <div className="text-sm text-slate-500 font-bold">MINS</div>
            </div>
         </HoloCard>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 flex-1 min-h-0">
        <HoloCard className="p-6 flex flex-col" glowColor="none">
           <h3 className="text-sm font-bold tracking-widest text-slate-400 mb-4 flex items-center gap-2">
             <Activity className="w-4 h-4 text-brand-emerald" /> GLOBAL INFRASTRUCTURE ROI
           </h3>
           <div className="flex-1 min-h-0 flex items-center justify-center bg-slate-900/50 rounded-xl border border-slate-800">
              {/* Fake chart placeholder or reuse MetricsChart */}
              <div className="w-full h-full p-4">
                 <MetricsChart dataKey="system_health" color="#00FF9D" name="System Health" />
              </div>
           </div>
        </HoloCard>

        <HoloCard className="p-6 overflow-y-auto custom-scrollbar" glowColor="none">
           <h3 className="text-sm font-bold tracking-widest text-slate-400 mb-4 flex items-center gap-2">
             <Briefcase className="w-4 h-4 text-brand-amber" /> EXECUTIVE AI SUMMARIES
           </h3>
           <div className="space-y-4">
              <div className="p-4 bg-slate-900/80 border border-slate-800 rounded-xl">
                 <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-bold text-slate-400 font-mono">Q2 SECURITY POSTURE</span>
                    <span className="text-[10px] bg-brand-emerald/10 text-brand-emerald px-2 py-1 rounded border border-brand-emerald/30">GENERATED BY AI</span>
                 </div>
                 <p className="text-sm text-slate-300 leading-relaxed">
                   DDoS mitigation algorithms successfully repelled 14 state-sponsored attacks this quarter. Zero downtime reported. AI predictive scaling saved an estimated $42,000 in redundant compute costs during the Black Friday peak.
                 </p>
              </div>
           </div>
        </HoloCard>
      </div>
    </div>
  );
}
